#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx ls | grep mybuilder || docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx inspect --bootstrap
